### ISSUE TITLE
Spree 2.3

### ISSUE THREAD

**Issue by novotarq** [joneslee85/spree_ajax_add_to_cart#5]
Maybe it would be good to support Spree 2.3?

You can find my try here: https://github.com/novotarq/spree_ajax_add_to_cart/tree/2-3-stable

**Comment by tomashn** [comment]
nice to have it as a gem

**Comment by joneslee85** [comment]
Hey guys, this stuff is getting too old and I am no longer up-to-date. Anyone keen to take over?

**Comment by novotarq** [comment]
@joneslee85 I think I could try :)

**Comment by joneslee85** [comment]
@novotarq I added you as collbarator
