### ISSUE TITLE
Spree 3.0 and my try to take over this gem

### ISSUE THREAD

**Issue by novotarq** [joneslee85/spree_ajax_add_to_cart#6]
I pushed some 3.0 code to my fork:
https://github.com/novotarq/spree_ajax_add_to_cart/tree/3-0-stable

Maybe I could take over this gem?

**Comment by joneslee85** [comment]
@novotarq sure, please do.

Do you want me to redirect my repo to yours or you want me to add you as full rights for this repo?

**Comment by novotarq** [comment]
I was thinking maybe of a redirect, but this is entirely up to you.

**Comment by joneslee85** [comment]
done
